# Generated by Django 5.0 on 2023-12-28 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epic_events', '0002_alter_collaborator_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='username',
        ),
    ]
