# Generated by Django 5.0 on 2023-12-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_events', '0003_remove_collaborator_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
