# Generated by Django 5.0 on 2023-12-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_events', '0004_collaborator_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='slug_name',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='slug_name',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='Date de naissance'),
        ),
    ]
