# Generated by Django 5.0 on 2023-12-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_events', '0005_rename_slug_name_company_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
