# Generated by Django 5.0 on 2023-12-31 17:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_events', '0006_customer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='epic_events.department'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('edition_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('total_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_paid', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('is_signed', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='epic_events.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
