# Generated by Django 5.0 on 2024-01-01 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_events', '0007_alter_collaborator_department_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='amount_paid',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant payé €'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='is_signed',
            field=models.BooleanField(default=False, verbose_name='Signé'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_amount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant total €'),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
