# Generated by Django 5.0 on 2024-01-02 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_events', '0008_contract_slug_alter_company_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='epic_events.customer'),
        ),
    ]
