# Generated by Django 5.0 on 2024-01-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_events', '0010_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='amount_paid',
            field=models.PositiveIntegerField(default=0, verbose_name='Montant payé €'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Montant total €'),
        ),
        migrations.AlterField(
            model_name='location',
            name='street_type',
            field=models.CharField(blank=True, choices=[('', ''), ('rue', 'rue'), ('impasse', 'impasse'), ('avenue', 'avenue'), ('boulevard', 'boulevard'), ('allée', 'allée'), ('chemin', 'Chemin')], max_length=100, null=True, verbose_name='Type de voie'),
        ),
    ]
