# Generated by Django 5.0 on 2024-01-03 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_events', '0011_alter_contract_amount_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('edition_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('attendees', models.PositiveIntegerField(default=0, verbose_name='Nombre de participants')),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin')),
                ('note', models.TextField(blank=True, max_length=2048, null=True)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='epic_events.contract')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='epic_events.location')),
                ('support', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
