# Generated by Django 5.0 on 2024-01-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_events', '0012_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug_form',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
