# Generated by Django 5.0.1 on 2024-01-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_events', '0013_location_slug_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='location',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de voie'),
        ),
    ]
